import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { Providers } from "./providers";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: [ "latin" ] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main className="container mx-auto p-6 max-w-screen-2xl">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
