import Navbar from "@/components/client/Navbar"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ReactNode } from "react"
import { Providers } from "../client/providers"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main className="container mx-auto max-w-screen-2xl bg-background p-6">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
